
-- create scheduler database schema
CREATE DATABASE `scheduler` /*!40100 DEFAULT CHARACTER SET latin1 */;

-- create user's category table:
CREATE TABLE `CATEGORY` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(300) NOT NULL,
  `DESCRIPTION` varchar(500) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- create TODO_USER table
ALTER TABLE TODO_USER
  ADD FOREIGN KEY (SUPERVISOR_ID) REFERENCES TODO_USER(ID);CREATE TABLE `TODO_USER` (
  `ID` int(11) NOT NULL,
  `USER_NAME` varchar(150) NOT NULL,
  `FIRST_NAME` varchar(150) NOT NULL,
  `LAST_NAME` varchar(150) NOT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  `CATEGORY_ID` int(11) NOT NULL,
  `SUPERVISOR_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CATEGORY_ID` (`CATEGORY_ID`),
  KEY `SUPERVISOR_ID` (`SUPERVISOR_ID`),
  CONSTRAINT `TODO_USER_ibfk_1` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`ID`),
  CONSTRAINT `TODO_USER_ibfk_2` FOREIGN KEY (`SUPERVISOR_ID`) REFERENCES `TODO_USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- create TODO Table.
CREATE TABLE `TODO` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(200) NOT NULL,
  `DUE_DATE` datetime NOT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `COMPLETED` tinyint(4) DEFAULT NULL,
  `COMPLETE_DATE` datetime DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `TODO_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `TODO_USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
