spring:
  profiles: development
  application:
    name: todo-service
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler?autoReconnect=true&useSSL=false
    username: root
    password: aDm1n!strator@2021
    maxActive: 5
    maxIdle: 1
    maxWait: 30000

  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true

server:
  port: 0
  
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  security:
    enabled: false

---

spring:
  profiles: uat
  application:
    name: todo-service
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler?autoReconnect=true&useSSL=false
    username: db_root
    password: password
    maxActive: 5
    maxIdle: 1
    maxWait: 30000

  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true

server:
  port: 0
  
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  security:
    enabled: false


